PYTHON_GATT_VERSION = 0.2.7
PYTHON_GATT_SOURCE = $(PYTHON_GATT_VERSION).tar.gz
PYTHON_GATT_SITE = $(call github,getsenic,gatt-python,e1b147d54ff199571b6c0b43bdd3a9e1ce03850c)
PYTHON_GATT_LICENSE = MIT
PYTHON_GATT_LICENSE_FILES = LICENSE
PYTHON_GATT_SETUP_TYPE = setuptools

$(eval $(python-package))
