#!/bin/sh
# sshd init-script
# supports inetd and pre-checking configuration

check_configuration() {
  echo "Checking sshd configuration..."

  # Make sure the ssh-keygen progam exists
  [ -x /usr/bin/ssh-keygen ] || { echo "  ...missing ssh-keygen"; exit 1; }

  # Check that the sshd_config file exists
  [ -f /etc/ssh/sshd_config ] || { echo "  ...missing sshd_config"; exit 1; }

  /usr/bin/ssh-keygen -A
}

umask 077

case "$1" in
  check)
    # inetd pre-check support
    # For each enabled key type in config, the respective keyfile is checked to
    # exist and be greater than zero size. The key pair are regenerated w/temp
    # names and upon completion, renamed to respective names.
    check_configuration
    ;;
  stop)
    echo -n "Stopping sshd: "
    killall sshd 2>/dev/null
    echo "OK"
    ;;
  start)
    # always check config if running manually
    [ -z "$rcS_" ] && check_configuration
    echo -n "Starting sshd: "
    /usr/sbin/sshd
    echo "OK"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {check|stop|start|restart}"
    false
esac
exit $?
