[global]
server.ssl_private_key: "/rodata/secret/rest-server/ssl/server.key"
server.ssl_certificate: "/rodata/secret/rest-server/ssl/server.crt"
server.ssl_certificate_chain: "/rodata/secret/rest-server/ssl/ca.crt"
