[summit-rcm]
provisioning_dir: "/data/secret/permanent/provisioning"
provisioning_ssl_private_key: "/rodata/secret/rest-server/ssl/provisioning.key"
provisioning_ssl_certificate: "/rodata/secret/rest-server/ssl/provisioning.crt"
provisioning_ssl_certificate_chain: "/rodata/secret/rest-server/ssl/provisioning.ca.crt"
device_server_key: "/data/secret/permanent/provisioning/dev.key"
device_server_csr: "/data/secret/permanent/provisioning/dev.csr"
device_server_cert: "/data/secret/permanent/provisioning/dev.crt"
